print("Why did the orange stop rolling down the hill?")
input("Wait for it...............")
print("Because it ran out of juice!")
input()
print("Why did the picture go to jail?")
input("Wait for it......")
print("Because it was framed!")
input()
print("What kind of tea is hard to swallow?")
input()
print("Reality.")