Name=input("What is your name")
print(f"I like your name {Name}")
name1=input("Name 1")
name2=input("Name 2")
name3=input("Name 3")
name4=input("Name 4")
noun1=input("Write a noun")
noun2=input("Write another noun")
noun3=input("Write one more noun")
adjective1=input("Name an adjective")
adjective2=input("Write an adjective")
adjective3=input("One more adjective please")
activity=input("Name an Activity")
songname=input("Name a song title")
verb=input("Write a verb")
pasttenseverb=input("Write a past tense verb")
print(f"Yesterday I went to {name1}'s birthday party.")
print(f"I got them a {noun1}.")
print(f"The party was {adjective1}.")
print(f"We started by playing {activity} and then there was a {verb} party.")
print(f"Lots of my friends were there but I mostly hung out with {name2}.")
print(f"We talked about {noun2} and how our friend {name3} is a {noun3}.")
print(f"During cake everyone {adjective2} and sang {songname}.")
print(f" I had a {pasttenseverb} time at the party and enjoyed celebrating {name4}.")
print(f"they are {adjective3} such a friend.")
print(f"Thanks for doing my Mad Libs {Name}")